server:
    port: 8088

urlCors: http://localhost:5173

springdoc.api-docs.path: /api-docs

logging:
    level:
        root: INFO
    file:
        name: /tmp/reaktor_timeTableServer.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
