spring:
    profiles:
        active: default
    jpa.hibernate.ddl-auto: validate   
    datasource:
     url: jdbc:mysql://localhost:3306/reaktor_timetableserver?createDatabaseIfNotExist=true
     username: root
     password: toor
     hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
 
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level.org.hibernate.SQL: info
  level: debug
server:
    port: 8088
urlCors: http://localhost:5173