spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/timetable
    username: root
    password: 7_ap49y4z$n
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8088
logging:
    level:
        root: WARN
    file:
        name: /tmp/reaktor_timeTableServer.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
urlCors: http://localhost:5173