server:
    port: 8088
springdoc.api-docs.path: /api-docs
logging:
    level:
        root: INFO
    file:
        name: /tmp/archivo.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB