spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/timetable
    username: root
    password: admin
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
    port: 8088
springdoc.api-docs.path: /api-docs
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level.org.hibernate.SQL: debug
  level: debug
urlCors: http://localhost:5173